version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    volumes: 
      - kane-elastic:/usr/share/elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    volumes:
      - kane-kibana:/usr/share/kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  kane-elastic:
  kane-kibana:
